//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class KediÜrün
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KediÜrün()
        {
            this.SİPARİŞ = new HashSet<SİPARİŞ>();
        }
    
        public int kediÜrünID { get; set; }
        public int tedarikçiNo { get; set; }
        public string ürünAd { get; set; }
        public int stokMiktarı { get; set; }
    
        public virtual TEDARİKÇİ TEDARİKÇİ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SİPARİŞ> SİPARİŞ { get; set; }
    }
}
